version: '3'
services:
  nextjs:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
      - NEXT_SKIP_API_ROUTES=1
      - NEXT_PUBLIC_APP_URL=http://localhost:3000
    env_file:
      - .env